declare const enum NapiEnvOffset64 {
  __size__ = 64,
  vptr = 0,
  sentinel = 8,
  js_vtable = 16,
  module_vtable = 24,
  id = 32,
  last_error = 40,
  last_error___size__ = 24,
  last_error_error_message = 40,
  last_error_engine_reserved = 48,
  last_error_engine_error_code = 56,
  last_error_error_code = 60,
}
declare const enum NapiTSFNOffset64 {
  __size__ = 320,
  async_resource = 0,
  async_resource___size__ = 32,
  async_resource_resource = 0,
  async_resource_async_context = 8,
  async_resource_async_context___size__ = 16,
  async_resource_async_context_async_id = 8,
  async_resource_async_context_trigger_async_id = 16,
  async_resource_is_some = 24,
  mutex = 32,
  cond = 80,
  queue_size = 88,
  queue = 96,
  async = 112,
  thread_count = 240,
  state = 248,
  dispatch_state = 252,
  context = 256,
  max_queue_size = 264,
  ref = 272,
  env = 280,
  finalize_data = 288,
  finalize_cb = 296,
  call_js_cb = 304,
  handles_closing = 312,
  async_ref = 313,
}
