declare const enum NapiEnvOffset32 {
  __size__ = 48,
  vptr = 0,
  sentinel = 8,
  js_vtable = 16,
  module_vtable = 20,
  id = 24,
  last_error = 28,
  last_error___size__ = 16,
  last_error_error_message = 28,
  last_error_engine_reserved = 32,
  last_error_engine_error_code = 36,
  last_error_error_code = 40,
}
declare const enum NapiTSFNOffset32 {
  __size__ = 184,
  async_resource = 0,
  async_resource___size__ = 32,
  async_resource_resource = 0,
  async_resource_async_context = 8,
  async_resource_async_context___size__ = 16,
  async_resource_async_context_async_id = 8,
  async_resource_async_context_trigger_async_id = 16,
  async_resource_is_some = 24,
  mutex = 32,
  cond = 56,
  queue_size = 60,
  queue = 64,
  async = 72,
  thread_count = 136,
  state = 140,
  dispatch_state = 144,
  context = 148,
  max_queue_size = 152,
  ref = 156,
  env = 160,
  finalize_data = 164,
  finalize_cb = 168,
  call_js_cb = 172,
  handles_closing = 176,
  async_ref = 180,
}
