name: CI wasm32-wasip1

on:
  workflow_call:

jobs:
  ci:
    timeout-minutes: 20
    name: CI wasm32-wasip1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-target-ci
      with:
        target: 'wasm32-wasip1'
        needs-wasi-sdk: 'true'
    - name: NPM Build
      shell: bash
      run: npm run build --workspaces --if-present
    - name: Build target
      run: npm run rebuild:w -w packages/test
    - name: Test Emscripten ESM library
      shell: bash
      run: npm run test -w packages/ts-transform-emscripten-esm-library
    - name: Test target
      run: npm run test:w -w packages/test
    - name: Test target (4GB)
      run: EMNAPI_TEST_4GB=1 npm run test:w -w packages/test
