name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - '**/docs/**'
    branches:
    - main
    - test-*
  pull_request:
    paths-ignore:
    - '**/*.md'
    - '**/docs/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  test:
    timeout-minutes: 15
    name: CI ${{ matrix.target.name }} (${{ matrix.mode }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
        - name: wasm32-unknown-emscripten
          setup: wasm32-unknown-emscripten
          needs_emscripten: 'true'
          needs_wasi_sdk: 'false'
          build: npm run rebuild -w packages/test
          test: npm run test -w packages/test
          browser: npm run test:browser -w packages/test
          test_4gb: EMNAPI_TEST_CONCURRENCY=2 EMNAPI_TEST_4GB=1 npm run test -w packages/test
        - name: wasm64-unknown-emscripten
          setup: wasm64-unknown-emscripten
          needs_emscripten: 'true'
          needs_wasi_sdk: 'false'
          build: MEMORY64=1 node ./packages/test/script/build-emscripten.js Debug
          test: MEMORY64=1 UV_THREADPOOL_SIZE=2 NODE_TEST_KNOWN_GLOBALS=0 node ./packages/test/script/test.js
          browser: npm run test:browser:wasm64 -w packages/test
          test_4gb: MEMORY64=1 EMNAPI_TEST_CONCURRENCY=2 EMNAPI_TEST_4GB=1 UV_THREADPOOL_SIZE=2 NODE_TEST_KNOWN_GLOBALS=0 node ./packages/test/script/test.js
        - name: wasm32-wasip1-threads (libemnapi-mt)
          setup: wasm32-wasip1-threads
          needs_emscripten: 'false'
          needs_wasi_sdk: 'true'
          build: npm run rebuild:wt -w packages/test
          test: npm run test:wt -w packages/test
          browser: npm run test:browser:wt -w packages/test
          test_4gb: EMNAPI_TEST_CONCURRENCY=2 EMNAPI_TEST_4GB=1 npm run test:wt -w packages/test
        - name: wasm32-wasip1-threads (libemnapi-basic-mt)
          setup: wasm32-wasip1-threads-js
          needs_emscripten: 'false'
          needs_wasi_sdk: 'true'
          build: EMNAPI_WASI_THREADS_LINK_BASIC_MT=1 npm run rebuild:wt -w packages/test
          test: EMNAPI_TEST_CONCURRENCY=1 npm run test:wt -w packages/test
          browser: npm run test:browser:wt -w packages/test
          test_4gb: EMNAPI_TEST_CONCURRENCY=2 EMNAPI_TEST_4GB=1 npm run test:wt -w packages/test
        - name: wasm32-wasip1
          setup: wasm32-wasip1
          needs_emscripten: 'false'
          needs_wasi_sdk: 'true'
          build: npm run rebuild:w -w packages/test
          test: npm run test:w -w packages/test
          browser: npm run test:browser:w -w packages/test
          test_4gb: EMNAPI_TEST_CONCURRENCY=2 EMNAPI_TEST_4GB=1 npm run test:w -w packages/test
        - name: wasm32-unknown-unknown
          setup: wasm32-unknown-unknown
          needs_emscripten: 'false'
          needs_wasi_sdk: 'true'
          build: npm run rebuild:wasm32 -w packages/test
          test: npm run test:wasm32 -w packages/test
          browser: npm run test:browser:wasm32 -w packages/test
          test_4gb: EMNAPI_TEST_CONCURRENCY=2 EMNAPI_TEST_4GB=1 npm run test:wasm32 -w packages/test
        mode:
        - node
        - browser
        - 4GB

    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-target-ci
      with:
        target: ${{ matrix.target.setup }}
        needs-emscripten: ${{ matrix.target.needs_emscripten }}
        needs-wasi-sdk: ${{ matrix.target.needs_wasi_sdk }}
        needs-browser: ${{ matrix.mode == 'browser' }}
    - name: NPM Build
      run: npm run build --workspaces --if-present
    - name: Build target
      run: ${{ matrix.target.build }}
    - name: Test target
      if: matrix.mode == 'node'
      run: ${{ matrix.target.test }}
      timeout-minutes: 3
    - name: Test target (4GB)
      if: matrix.mode == '4GB'
      run: ${{ matrix.target.test_4gb }}
      timeout-minutes: 3
    - name: Test target in browser
      if: matrix.mode == 'browser'
      run: ${{ matrix.target.browser }}
      timeout-minutes: 10

  napi-versions:
    timeout-minutes: 10
    name: CI Node-API versions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-target-ci
      with:
        target: wasm32-unknown-emscripten
        needs-emscripten: 'true'
    - name: Test building Node-API versions
      run: npm run test:version
      timeout-minutes: 5

  package-tests:
    timeout-minutes: 10
    name: CI ${{ matrix.package.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
        - name: Emscripten ESM library
          target: ts-transform-emscripten-esm-library
          needs_wasi_sdk: 'false'
          build: npm run build -w packages/ts-transform-emscripten-esm-library -w packages/rollup-plugin-emscripten-esm-library
          test: npm run test -w packages/ts-transform-emscripten-esm-library
        - name: '@emnapi/runtime'
          target: runtime
          needs_wasi_sdk: 'false'
          build: npm run build -w packages/shared -w packages/runtime
          test: npm run test -w packages/runtime
        - name: '@emnapi/wasi-threads'
          target: wasm32-wasip1-threads
          needs_wasi_sdk: 'true'
          build: npm run build -w packages/shared -w packages/wasi-threads
          test: node ./packages/wasi-threads/test/build.js && npm run test -w packages/wasi-threads

    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-target-ci
      with:
        target: ${{ matrix.package.target }}
        needs-wasi-sdk: ${{ matrix.package.needs_wasi_sdk }}
        needs-v8-headers: 'false'
    - name: Build package
      run: ${{ matrix.package.build }}
    - name: Test package
      run: ${{ matrix.package.test }}
      timeout-minutes: 2
