name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - '**/docs/**'
    branches:
    - main
    - test-*
  pull_request:
    paths-ignore:
    - '**/*.md'
    - '**/docs/**'

permissions:
  id-token: write
  contents: write

jobs:
  wasm32-unknown-emscripten:
    timeout-minutes: 15
    name: CI wasm32-unknown-emscripten
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-target-ci
      with:
        target: 'wasm32-unknown-emscripten'
        needs-emscripten: 'true'
    - name: NPM Build
      run: npm run build --workspaces --if-present
    - name: Build target
      run: npm run rebuild -w packages/test
    - name: Test Emscripten ESM library
      run: npm run test -w packages/ts-transform-emscripten-esm-library
    - name: Test building Node-API versions
      run: npm run test:version
    - name: Test target
      run: npm run test -w packages/test
      timeout-minutes: 3
    - name: Test target (4GB)
      run: EMNAPI_TEST_4GB=1 npm run test -w packages/test
      timeout-minutes: 3

  wasm64-unknown-emscripten:
    timeout-minutes: 15
    name: CI wasm64-unknown-emscripten
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-target-ci
      with:
        target: 'wasm64-unknown-emscripten'
        needs-emscripten: 'true'
    - name: NPM Build
      run: npm run build --workspaces --if-present
    - name: Build target
      run: MEMORY64=1 node ./packages/test/script/build-emscripten.js Debug
    - name: Test target
      run: MEMORY64=1 UV_THREADPOOL_SIZE=2 NODE_TEST_KNOWN_GLOBALS=0 node ./packages/test/script/test.js
      timeout-minutes: 3
    - name: Test target (4GB)
      run: MEMORY64=1 EMNAPI_TEST_4GB=1 UV_THREADPOOL_SIZE=2 NODE_TEST_KNOWN_GLOBALS=0 node ./packages/test/script/test.js
      timeout-minutes: 3

  wasm32-wasip1-threads:
    timeout-minutes: 15
    name: CI wasm32-wasip1-threads (libemnapi-mt)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-target-ci
      with:
        target: 'wasm32-wasip1-threads'
        needs-wasi-sdk: 'true'
    - name: NPM Build
      run: npm run build --workspaces --if-present
    - name: Build target
      run: npm run rebuild:wt -w packages/test
    - name: Test @emnapi/wasi-threads
      run: |
        node ./packages/wasi-threads/test/build.js
        npm run test -w packages/wasi-threads
      timeout-minutes: 1
    - name: Test target
      run: npm run test:wt -w packages/test
      timeout-minutes: 3
    - name: Test target (4GB)
      run: EMNAPI_TEST_4GB=1 npm run test:wt -w packages/test
      timeout-minutes: 3

  wasm32-wasip1-threads-use-js:
    timeout-minutes: 15
    name: CI wasm32-wasip1-threads (libemnapi-basic-mt)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-target-ci
      with:
        target: 'wasm32-wasip1-threads-js'
        needs-wasi-sdk: 'true'
    - name: NPM Build
      run: npm run build --workspaces --if-present
    - name: Build target
      run: EMNAPI_WASI_THREADS_LINK_BASIC_MT=1 npm run rebuild:wt -w packages/test
    - name: Test target
      run: npm run test:wt -w packages/test
      timeout-minutes: 3
    - name: Test target (4GB)
      run: EMNAPI_TEST_4GB=1 npm run test:wt -w packages/test
      timeout-minutes: 3

  wasm32-wasip1:
    timeout-minutes: 15
    name: CI wasm32-wasip1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-target-ci
      with:
        target: 'wasm32-wasip1'
        needs-wasi-sdk: 'true'
    - name: NPM Build
      run: npm run build --workspaces --if-present
    - name: Build target
      run: npm run rebuild:w -w packages/test
    - name: Test target
      run: npm run test:w -w packages/test
    - name: Test target (4GB)
      run: EMNAPI_TEST_4GB=1 npm run test:w -w packages/test

  wasm32-unknown-unknown:
    timeout-minutes: 15
    name: CI wasm32-unknown-unknown
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-target-ci
      with:
        target: 'wasm32-unknown-unknown'
        needs-wasi-sdk: 'true'
    - name: NPM Build
      run: npm run build --workspaces --if-present
    - name: Build target
      run: npm run rebuild:wasm32 -w packages/test
    - name: Test target
      run: npm run test:wasm32 -w packages/test
    - name: Test target (4GB)
      run: EMNAPI_TEST_4GB=1 npm run test:wasm32 -w packages/test
