name: Debug

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  debug:
    name: Debug with upterm
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-target-ci
      with:
        target: 'debug'
        needs-emscripten: 'true'
        needs-wasi-sdk: 'true'
    - name: Setup debug session
      uses: ./.github/actions/debugger
      if: ${{ github.event_name == 'workflow_dispatch' }}
