name: Debug action

description: Run the build with debugging enabled

runs:
  using: composite
  steps:
  - name: Setup upterm session
    uses: owenthereal/action-upterm@v1
    with:
      limit-access-to-actor: true
